### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [opensass/cli#11]
- [ ] Implement a build error overlay component.
- [ ] Fix `yew` proc macros re-export.
- [ ] Improve the `Image` component, seo, accessibility, performance, etc.
- [ ] Improve the `Link` component, seo, accessibility, performance, etc.
- [x] Implement a `Head` component.
- [x] Add prefetch mechanism to `Router` component.
- [x] Add prefetch mechanism to `Link` component.
